"""add metadata to sessiontable

Revision ID: 778ece3f04f8
Revises: dfd983df7648
Create Date: 2025-03-23 23:42:03.132919

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "778ece3f04f8"
down_revision: Union[str, None] = "dfd983df7648"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stream_sessions", sa.Column("device_name", sa.String(), nullable=True)
    )
    op.add_column("stream_sessions", sa.Column("device_id", sa.String(), nullable=True))
    op.add_column(
        "stream_sessions", sa.Column("detect_model_name", sa.String(), nullable=True)
    )
    op.add_column(
        "stream_sessions", sa.Column("detect_model_version", sa.String(), nullable=True)
    )
    op.add_column(
        "stream_sessions",
        sa.Column("stream_start", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.add_column(
        "stream_sessions",
        sa.Column("stream_end", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stream_sessions", "stream_end")
    op.drop_column("stream_sessions", "stream_start")
    op.drop_column("stream_sessions", "detect_model_version")
    op.drop_column("stream_sessions", "detect_model_name")
    op.drop_column("stream_sessions", "device_id")
    op.drop_column("stream_sessions", "device_name")
    # ### end Alembic commands ###
