version: "3.8"
services:
  postgres:
    image: postgres
    container_name: detection-pg-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test1234!
      POSTGRES_DB: ObjectDetectionDb
    ports:
      - "5432:5432"
# If data has to be stored after restart, mount the volume
